name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # 특정 브랜치로 푸시 시 실행

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5
      - name: Navigate to Terraform directory
        run: cd ./

      - name: Navigate to Terraform directory
        run: tree

      - name: Check if ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names my-repository-ecs || echo "ECR repository does not exist"
        continue-on-error: true

      - name: Import ECR repository if it exists
        run: |
          if [ $? -eq 0 ]; then
            terraform import aws_ecr_repository.example my-repository-ecs;
          fi
        continue-on-error: true

      - name: Check if IAM Role exists
        run: |
          aws iam get-role --role-name ecsTaskExecutionRole || echo "IAM role does not exist"
        continue-on-error: true

      - name: Import IAM role if it exists
        run: |
          if [ $? -eq 0 ]; then
            terraform import aws_iam_role.ecs_task_execution_role ecsTaskExecutionRole;
          fi
        continue-on-error: true

      - name: Run terraform plan
        run: terraform plan

      - name: Run terraform apply
        run: terraform apply -auto-approve

